name: CI
on:
  - pull_request
  - push

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install NPM dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
  Test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: Lint
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Pulsar
        uses: pulsar-edit/action-pulsar-dependency@v3.2
      - name: Install dependencies
        run: npm ci
      - name: Run the headless Pulsar Tests
        uses: coactions/setup-xvfb@v1.0.1
        with:
          run: pulsar --test spec
